### ISSUE TITLE
this API has been removed.

### ISSUE THREAD

**Issue by jamninetyfive** [jybp/twitch-downloader#1]
https://api.twitch.tv/api/vods/509862982/access_token?client_id=m0k44g5ltfwowryzw1zozh68buf7bf

this API has been removed.

**Comment by jybp** [comment]
@jamninetyfive Thank you for letting me know and sorry for the delay.

Please use the latest release (1.1) to fix the issue:
https://github.com/jybp/twitch-downloader/releases

Let me know if everything's good.
