### ISSUE TITLE
Twitch video URL format has changed

### ISSUE THREAD

**Issue by SDXC** [jybp/twitch-downloader#11]
It seems Twitch changed its video url format by adding the channel name:
https://www.twitch.tv/letsgameitout/video/2182428086

Before the video url was like this:
https://www.twitch.tv/videos/2182428086

When trying to fetch the VOD info the following error occurs:
`Retrieving name for URL https://www.twitch.tv/letsgameitout/video/2182428086 failed: Cannot extract VOD ID or clip slug from URL`

Manually changing the url to the format like before works for now, but it'd be a good idea to support both ways.

**Comment by jybp** [comment]
Support for those kind of URLs added in https://github.com/jybp/twitch-downloader/releases/tag/v3.6
