### ISSUE TITLE
Cannot download Twitch VOD that has "\" in the stream title

### ISSUE THREAD

**Issue by DomDXD** [jybp/twitch-downloader#13]
Can you try to download this stream?
https://www.twitch.tv/videos/2296973517

I get this error:

D:\>dl -url https://www.twitch.tv/videos/2296973517 -q best
Cannot create file Timota_74 - (18+) WRF-Rally Is the Word! no assists\h-pattern\1080DOR\Softlock\sequencial-Welcome to the simulation channel! (1080p60).mp4: open Timota_74 - (18+) WRF-Rally Is the Word! no assists\h-pattern\1080DOR\Softlock\sequencial-Welcome to the simulation channel! (1080p60).mp4: The system cannot find the path specified.

Would it be possible to add a -n option and let me type the filename that I want to use?

Thank you for your app. It's very easy to use and the download speed is very good too!
Dominic.

ok, I downloaded your code and did some testing and modifications and I was able to fix this problem. Another issue that I was facing was when the streamer had two different streams but with the same title then your app would say that the file already exist even if it's a new download URL.

I only have a bit of experience using vb.net and this is the fist time I hear about the Go language so I think what I did is working because I created a test twitch account and went live and added all the characters you cannot use in a file name for windows ( \ / : * ? " < > | )  and I was able to download the VOD just fine.  
This is the link to my VOD if you want to test it: https://www.twitch.tv/videos/2305306358 (link will be there for only 6 days)
It removed all of those characters from the stream title (this is a \ / : * ? " < > | test) to (dom_dxdtest - this is a          test - 2024-11-19 12_27_43 (1080p).ts)

So this is what I changed:

line 30 in the twitchdl.go file is:
return fmt.Sprintf("%s - %s", vod.Owner.DisplayName, vod.Title), nil

and I changed it to this:
streamTitle := vod.Title
streamTitle = strings.Replace(streamTitle, "\\", "", -1)
streamTitle = strings.Replace(streamTitle, "/", "", -1)
streamTitle = strings.Replace(streamTitle, ":", "", -1)
streamTitle = strings.Replace(streamTitle, "*", "", -1)
streamTitle = strings.Replace(streamTitle, "?", "", -1)
streamTitle = strings.Replace(streamTitle, `"`, "", -1)
streamTitle = strings.Replace(streamTitle, "<", "", -1)
streamTitle = strings.Replace(streamTitle, ">", "", -1)
streamTitle = strings.Replace(streamTitle, "|", "", -1)
		
currentTime := time.Now()
			
return fmt.Sprintf("%s - %s - %s", vod.Owner.DisplayName, streamTitle, currentTime.Format("2006-1-2 15_4_5")), nil

Now that removes all the the character you can't use in a filename and I also added the date and time to avoid getting the error message that the file already exist.

Another thing I noticed is that you are renaming the download file from a .ts to .mp4. It is not converting the file to that format, it's only a file rename. So when the file was downloaded it didn't show a thumbnail of the video and when I put my mouse on the file it didn't show the usual info like the duration of the video.
So in your main.go file (line 93) I changed the extension back to .ts

To convert the file very fast I use ffmpeg with this command:
ffmpeg -i input.ts -c:v copy -c:a copy output.mp4
Then I delete the .ts file and it only takes seconds for a 3 hour long stream.

Cheers and have a good day,
Dominic.

**Comment by jybp** [comment]
Can't you just use the `-o` flag?

**Comment by jybp** [comment]
https://github.com/jybp/twitch-downloader/commit/5a417331d706ced16a5218b938baa9c715a11bd7

**Comment by DomDXD** [comment]
Yes the -o flag works too, it's ok. Thanks

**Comment by jybp** [comment]
> Another thing I noticed is that you are renaming the download file from a .ts to .mp4.

Yes, I didn't check the actual container format beforehand.

```
ffprobe -v quiet -print_format json -show_format test.mp4  | jq .format.format_name
"mpegts"
```

I guess you're right, will rename to .ts
