### ISSUE TITLE
OAuth token is missing

### ISSUE THREAD

**Issue by keyle** [jybp/twitch-downloader#2]
Any solution for this issue? ta

`Retrieving video informations for VOD ...  failed: 401
https://api.twitch.tv/helix/videos?id=...
{"error":"Unauthorized","status":401,"message":"OAuth token is missing"}`

**Comment by ChrisDBaldwin** [comment]
Header needs to include {'Authorization': "Bearer " + access_token} with the Header, at line 127 of twitch.go. Adding an additional command arg for access_token would solve this. Access tokens can be found using browser dev tools and inspecting the cookies.

![image](https://user-images.githubusercontent.com/3086357/103024025-aaac1980-4514-11eb-9a21-d94b19c5837e.png)

**Comment by jybp** [comment]
I've just released v2.0 that fixes this issue: https://github.com/jybp/twitch-downloader/releases
