### ISSUE TITLE
400 errors on DL

### ISSUE THREAD

**Issue by colinmccann** [jybp/twitch-downloader#6]
I'm wondering if Twitch switched it up again, and is somehow preventing this downloader from working as expected.
I tried to dl but received a 400. Stacktrace below.
(I opened the stream in a browser to confirm it would load, url is correct, etc)

/Users/colin/dev/go/src/twitch-downloader/cmd/twitchdl git:(master)λ ./twitchdl -v -url https://www.twitch.tv/videos/123 -q best
invalid status code 400
POST /gql HTTP/1.1
Host: gql.twitch.tv
User-Agent: Go-http-client/1.1
Content-Length: 214
Client-Id: TwitchClientID
Accept-Encoding: gzip

{"operationName":"VideoMetadata","variables":{"channelLogin":"","videoID":"1215035079"},"extensions":{"persistedQuery":{"version":1,"sha256Hash":"226edb3e692509f727fd56821f5653c05740242c82b0388883e0c0e75dcbf687"}}}
github.com/jybp/twitch-downloader/twitch.(*Client).do
	/Users/colin/dev/go/src/twitch-downloader/twitch/twitch.go:97
github.com/jybp/twitch-downloader/twitch.(*Client).VOD
	/Users/colin/dev/go/src/twitch-downloader/twitch/twitch.go:132
github.com/jybp/twitch-downloader.Name
	/Users/colin/dev/go/src/twitch-downloader/twitchdl.go:26
main.run
	/Users/colin/dev/go/src/twitch-downloader/cmd/twitchdl/main.go:65
main.main
	/Users/colin/dev/go/src/twitch-downloader/cmd/twitchdl/main.go:46
runtime.main
	/usr/local/go/src/runtime/proc.go:255
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1581
Retrieving name for URL https://www.twitch.tv/videos/123 failed
main.run
	/Users/colin/dev/go/src/twitch-downloader/cmd/twitchdl/main.go:67
main.main
	/Users/colin/dev/go/src/twitch-downloader/cmd/twitchdl/main.go:46
runtime.main
	/usr/local/go/src/runtime/proc.go:255
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1581

**Comment by jybp** [comment]
Just used it and it works properly.
Your output looks weird, did you manually edit it? `https://www.twitch.tv/videos/123` obviously doesn't exist so the 400 is expected.

I see that you-ve pulled the code, to use the program you must specify a twitch client-id, either with the flag or in a build tag as explained here: https://github.com/jybp/twitch-downloader/tree/v3.0#build-from-source

You should use twitch.tv 's own client id. It can be found here: https://github.com/jybp/twitch-downloader/blob/v3.0/.goreleaser.yml#L10

**Comment by P-Gaz** [comment]
Hi, thanks for your beautiful software, i have a similar Issue, i didn't know if I should recreate another thread or not.
I have tried to download some chat (on Windows or Linux) and all the time i have an error :
`The remote server returned an error: (400) Bad Request`

The only chat i have download with success is a little that didn't exceed thirty minutes, could you give me a hand please?.

**Comment by jybp** [comment]
@P-Gaz You need to share the full command you are using for me to help.
