### ISSUE TITLE
VODs with ? in the title

### ISSUE THREAD

**Issue by Pt0r** [jybp/twitch-downloader#7]
Hi! I've run into an issue when trying to download vods that have ? in the title, since the filename is based on the title and ? is not an allowed character in filenames, at least not in windows. An option to change the filename before starting the download could be a nice feature.

**Comment by jybp** [comment]
You can use the `-o` flag to force a filename. On Windows:
```
.\twitchdl.exe -url "https://www.twitch.tv/videos/123456" -o myfilename.mp4 -q best
```
