### ISSUE TITLE
Get the url of the direct download

### ISSUE THREAD

**Issue by rohidjetha** [jybp/twitch-downloader#8]
Is it possible to get the direct download url of a twitch vod/clips?

**Comment by jybp** [comment]
Not from the current exported funcs. 
For clips, the URL is available in `dlURL` here:  https://github.com/jybp/twitch-downloader/blob/master/twitchdl_clip.go#L36
For VODs, it's served over HLS. The manifest URL is inside `u` here: https://github.com/jybp/twitch-downloader/blob/8e7119e98161b8f2e0cd4eecb1c5a2542bcfeed1/twitch/twitch.go#L210

**Comment by rohidjetha** [comment]
Thanks, I wanted that so php don’t have to download and user can download it directly on their computer
